src/apollo/queries.js

- Seems that because this timestamp_lt query param was removed it didn't fetch block data properly. Is there a reason for removing it? And should I look more into it?
```
timestamp_lt: ${
timestamp + 600
```

Added back previous get blocks function

---

src/contexts/GlobalData.js

Info on lower timeframes is now calculated even when data on higher timeframes is not yet available. Previously, info on any timefram wasn't really computed until two weeks after an indexed transaction was submitted to the factory and picked up by the subgraph. Not the case anymore.

Partial info calculation

---

src/components/DropdownSelect/index.js

Prefetch network logos to avoid jerky loading
https://user-images.githubusercontent.com/102727631/164243395-33bd4fc9-0294-4b15-ac82-69feddf5a003.mp4
Now network logos are prefetched to so when you click the selector its loaded from browser cache. 
Also given fixed width and height to the parent element to avoid movement of network name
Check network switcher after clearing browser cache and it should load without jerking.

Prefetch network logos to avoid jerky loading

---

src/apollo/queries.js
src/components/ComulativeNetworkDataCard/index.js
src/components/ComulativeNetworkDataCard/styled.js
src/components/LocalLoader/index.js
src/components/StackedChart/CrosshairTooltip/index.js
src/components/StackedChart/Header/index.js
src/components/StackedChart/index.js
src/constants/index.js
src/contexts/Dashboard.js
src/pages/DashboardPage.js

Relative to #41 
Done:
- Bit of layout change to the dashboard page
- Load each component in the dashboard separately
- Add cumulative `Volume` data card
- Add cumulative `Trades` data card
1.  Open the page `Dashboard`
There are also changes that include the transactions historical data, that are not required for the cumulative data cards but are needed for the new transactions card (WIP)

feat: add comulative data for volume and trades

---

src/apollo/queries.js
src/components/ComulativeNetworkDataCard/index.js
src/components/ComulativeNetworkDataCard/styled.js
src/components/Icon/index.tsx
src/components/Icon/styled.tsx
src/components/LocalLoader/index.js
src/components/NetworkDataCardWithDialog/Dialog/index.tsx
src/components/NetworkDataCardWithDialog/index.tsx
src/components/NetworkDataCardWithDialog/styled.tsx
src/contexts/Dashboard.js
src/pages/DashboardPage.js

Related to #41 
Done:
1.  Open the page `dashboard`
The chart loading is pretty slow (same as the trades' one), especially when loading the data for the `Gnosis chain`; `Gnosis` takes up to an average of ~1.3s per query (when returning 1000 results), compare to 800ms for the others chains. So the chart loading total time is around 1-1.5m.

feat: add wallets data card to dashboard

---

src/apollo/queries.js
src/contexts/Dashboard.js

Optimize the `swaps` and `mints` queries by querying the two entities directly at the same time.
|Before |After |
--- | --- |
|2:27m|1:40m|
|2:10m|1:57m|
|2:15m|1:46m|
With these changes, the chart should load faster by at least ~20s.
1.  Open the page `dashboard`

feat: optimize mints and swaps queries

---

src/App.js
src/Theme/index.js
src/components/DoubleLogo/index.js
src/components/DropdownSelect/index.js
src/components/GlobalChart/index.js
src/components/NetworkDataCardWithDialog/Dialog/styled.tsx
src/components/Search/index.js
src/components/SideNav/index.js
src/pages/DashboardPage.js

There were multiple inconsistencies with elements overlapping when opening dropdowns, especially in the mobile viewport; this PR fixes them.
1.  Switch to mobile view

fix mobile view bugs

---

src/contexts/Dashboard.js
src/pages/DashboardPage.js

Fix a bug that was causing an erroneous data aggregation regarding the `Trades` and `Wallets` cards & charts.
The problem caused confusion since the 24h data wasn't matching with the latest values displayed by the corresponding chart.
Done:
1.  Open the page `dashboard`
There may be the case when the values still don't match, but that's because the chart loading takes a while, and in the meantime there could be new transactions (in any case it's a minor difference)

fix: wrong data aggregation

---

src/components/FarmingList/ListItem.tsx

Fix rewards path to swapr.eth.limo
This needs to be merged once swapr changes are deployed

Fix rewards path to swapr.eth.limo

---

src/utils/index.js

Fixes #75 
Add `/pool` prefix to links pointing to `add` and `remove` liquidity on swapr-dapp.
1.  Open the page `tokens` and click any pair
2. Open the page `accounts` and click any account
We should merge this PR when the change to the routes is deployed on swapr-dapp.

fix: add pool prefix to links

---

src/apollo/queries.js

Fixes #66
Display the first 200 pairs on the `pairs` page, just like the `tokens` page.
1.  Open the page `pairs`

fetch the first 200 pairs

---

src/apollo/queries.js

Fix the slow loading of the top 200 pairs on the overview page, which was causing the queries to take more than `50s`.
1.  Open the page `overview`
After digging and trying to optimize the query, I found out that it's a lot faster to query for the first `1000` entities and pick the first one than ask only for the first one directly in the query.

fix slow loading of top pairs

---

src/apollo/queries.js
src/components/ComulativeNetworkDataCard/index.js
src/components/ComulativeNetworkDataCard/styled.js
src/constants/index.tsx
src/contexts/User.js
src/hooks/useSwprPrice.ts
src/pages/DashboardPage.js
src/pages/GlobalPage.js

Add a redirect link to the fee receivers of each network from the `Dashboard`, inside the `Uncollected fees` card.
This PR also fixes a few queries that were failing due to a too large payload and an error when caching the query.
[scrnli_7_14_2022_9-16-10 PM.webm](https://user-images.githubusercontent.com/9011637/179065270-2a1db714-1582-476e-a097-9969b45631e2.webm)
1.  Open the page `Dashboard`

fee receiver lookup from dashboard

---

src/Theme/index.jsx
src/components/Chart/CrosshairTooltip/index.jsx
src/components/Chart/Header/index.jsx
src/components/Chart/Header/styled.jsx
src/components/Chart/index.jsx
src/utils/index.jsx

Fixes #106 
Add the option to aggregate the charts on the `overview` page by week.
The `BY WEEK` button is enabled only when the active time filter is `1M` or `1Y`, and it's automatically disabled when the time filter is `1W`.
[scrnli_9_19_2022_11-16-42 PM.webm](https://user-images.githubusercontent.com/9011637/191119147-88ccc04e-c9ac-4237-a759-05f4c5015015.webm)
1.  Open the page `Overview`

feat: add weekly aggregation to overview charts

---

src/constants/index.tsx

Fix #108.
Replace the old fee receiver address for Gnosis chain.

fix: replace old gnosis fee receiver

---

src/apollo/queries.js
src/components/FarmingList/ListItem.jsx
src/components/FarmingList/index.jsx
src/components/PairCard/index.jsx
src/constants/index.tsx
src/pages/FarmPage.jsx
src/utils/index.jsx

Fixes #60.
Add farm owner to the list as `DXdao` or `Other` and a panel indicating the owner in the details page (only if the campaign is created by the dao).

feat: differentiate dxdao created campaigns

---

src/utils/index.jsx

Fixed #115.
Use gnosisscan instead of blockscout.

replace blockscout with gnosisscan

---

src/contexts/Dashboard.jsx

After the `uncollected-fees` service's update the returned value for the gnosis chain changed, these changes fix the issue.

use new uncollected fees value for gnosis

---

src/Theme/index.jsx
src/components/LiquidityPositionsDropdown/styled.jsx
src/components/SideNav/index.jsx
src/components/TxnList/index.jsx

minor fixes

---

src/components/Chart/index.jsx

Fix an issue that was causing the overview charts to break when switching to the `1W` while the `BY WEEK` toggle was active.

fix: check for existing past value
